Repository thedevdojo/tails, pull requests merged in 2020-09, with the labels that each got.

#40 Adding Featured content with tiled images
  components/featured-content-tiles.html
Labels: hacktoberfest

#35 Adding New Pricing selector component
  components/pricing-select.html
Labels: hacktoberfest

#30 Proposal: Add dashboard widgets
  components/dashboard-widgets.html
Labels: hacktoberfest

#32 adding a pagination tailwind components
  components/pagination.html
Labels: hacktoberfest

#34 Add a comment to landmark about TailwindCSS customization options.
  templates/landmark.html
Labels: hacktoberfest

#29 Ref #8: alerts component
  components/alerts-ui.html
Labels: hacktoberfest

#26 Adding new feature component
  components/feature-content-course.html
Labels: hacktoberfest

#28 Ref #2: login form component
  components/login-form-simple.html
Labels: hacktoberfest

#27 Adding new testimonial component
  components/single-testimonial.html
Labels: hacktoberfest

#43 Re-uploaded deleted pricing select component
  components/pricing-select.html
Labels: help wanted

#47 Component: Buttons inspired by GitHub
  components/buttons-social.html
Labels: component, question

#36 Adding New Contact form component
  components/contact-form.html
Labels: hacktoberfest

#37 Added Registration Form Tailwind CSS Component
  components/Registration-form-full.html
Labels: hacktoberfest

#49 Adding information modal
  components/information-modal.html
Labels: component

#51 Tags component
  components/tags.html
Labels: component, enhancement

#58 Add loading component
  components/loader-dots.html
Labels: component, enhancement, hacktoberfest

#56 Adding new Alert component
  components/alert-minimal.html
Labels: component, enhancement, hacktoberfest
