Repository thedevdojo/tails, pull requests merged in 2020-10, with the labels that each got.

#60 Update information modal.
  components/information-modal.html
  components/modal-information.html
Labels: component, enhancement, hacktoberfest

#111 Fix typo in CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation

#104 improved emojis 😃
  CONTRIBUTING.md
Labels: documentation

#61 Adding new component called comment-thread
  components/comment-thread.html
Labels: component, enhancement, hacktoberfest

#109 Hey, re-adding my work on the pricing component.
  components/pricing-clean.html
Labels: component, enhancement

#75 Add Modal Warning
  components/modal-warning.html
Labels: hacktoberfest

#95 Adding new discount component
  components/discount-code.html
Labels: component, enhancement, hacktoberfest

#114 Adding new notification component #2
  components/notification-simple.html
Labels: component, enhancement

#57 add form-login-dark.html
  components/form-login-dark.html
Labels: component, enhancement, hacktoberfest

#64 Adding Skeleton Component
  components/skeleton-cards.html
Labels: component, enhancement

#136 Adding new modal login component
  components/modal-login.html
Labels: component, enhancement, hacktoberfest

#140 Updating form-login-dark.html
  components/form-login-dark.html
Labels: enhancement

#59 Add newsletter component (#48)
  components/newsletter.html
Labels: changes requested, component, enhancement, hacktoberfest, hacktoberfest-accepted

#154 Added footer component
  components/footer.html
Labels: component, enhancement, hacktoberfest-accepted

#170 Add event notice cards
  components/event-cards.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#179 Add icons component with different icon styles.
  components/icons-simple.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#185 Footer Simple Component
  components/footer-simple.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#206 added registration-split-form
  components/form-registration-full.html
Labels: hacktoberfest, hacktoberfest-accepted

#183 Add File uploader
  components/file-uploader.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#74 Added a responsive blog-post card component
  components/blog-post-card.html
Labels: component, enhancement

#121 feat: Adding the hero-minimal-meditate
  components/hero-minimal-meditate.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#127 Added frequently asked question Component with dropdown list
  components/faq-list-dropdown.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#128 Minimal Contact Section Component
  components/contact-section-component.html
Labels: component, enhancement

#132 Steps Infographic Component
  components/steps-infographic-component.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#96 Adding a new hero component
  components/hero-shop.html
Labels: changes requested, hacktoberfest, hacktoberfest-accepted

#67 Adding new login page component
  components/form-registration-centered.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#87 New Hero Component Delivery
  components/hero-delivery.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#89 Adding New Hero Review with Trial Button Component Left Background
  components/hero-trial-review2.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#124 adding simple search bar
  components/simple-searchbar.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#134 added 404_page_not_found component
  components/404_not_found_page_component.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#143 Creating contact-form
  components/contact-form.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#196 Add subscribe-modal component
  components/subscribe-modal.html
Labels: hacktoberfest, hacktoberfest-accepted

#186 Article list component
  components/card-boxes.html
Labels: hacktoberfest, hacktoberfest-accepted

#181 Add pricing with form
  components/pricing-with-form.html
Labels: hacktoberfest, hacktoberfest-accepted

#156 Profile card Component
  components/profile-card.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#160 Adding a new testimonial section having sticky notes look
  components/testimonial-sticky-notes.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#174 check this out
  components/portfolio.html
Labels: changes requested, hacktoberfest, hacktoberfest-accepted

#175 Adding a component for dropdown
  components/dropdown-simple.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#239 Adding new faq accordion component
  components/faq-accordion.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#247 Adding a chatbox one component
  components/alert-chat.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#246 Floating message notification
  components/alert-customer-chat.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted

#214 Added a media card component and Bottom Navigation component
  components/bottom-navigation.html
  components/card-media.html
Labels: hacktoberfest-accepted

#271 Adding a new Hero for events
  components/hero-event.html
Labels: component, hacktoberfest-accepted

#270 Adding checkout form
  components/form-checkout.html
Labels: component, hacktoberfest-accepted

#259 Add style guide section to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#249 Weather Card Added
  components/weather-card.html
Labels: component, hacktoberfest-accepted

#264 cookie-policy.html and page-not found.html
  components/cookie-policy.html
  components/page-not-found-404.html
Labels: component, hacktoberfest-accepted

#236 add connect people suggestion list
  components/connect-people.html
Labels: component, hacktoberfest-accepted

#250 Add modal rating component
  components/modal-rating.html
Labels: component, hacktoberfest-accepted

#256 added signup-page.html
  components/signup-page.html
Labels: component, hacktoberfest-accepted

#257 Fix button corners on GitHub Buttons
  components/button-github.html
Labels: component, enhancement, hacktoberfest, hacktoberfest-accepted
